apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-bp
  namespace: default
#automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-bp-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: deploy-bp
type: kubernetes.io/service-account-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-bp-role
rules: # ## Customize these to meet your requirements ##
- apiGroups:
  - ""
  - apps
  - batch
  - extensions
  - policy
  - rbac.authorization.k8s.io
  - roles.rbac.authorization.k8s.io
  - authorization.k8s.io
  - networking.k8s.io
  resources:
  - secrets
  - configmaps
  - deployments
  - endpoints
  - horizontalpodautoscalers
  - jobs
  - limitranges
  - namespaces
  - nodes
  - pods
  - persistentvolumes
  - persistentvolumeclaims
  - resourcequotas
  - replicasets
  - replicationcontrollers
  - statefulsets
  - serviceaccounts
  - services
  - role
  - rolebindings
  - ingresses
  verbs:
  - list
  - get
  - watch
  - create
  - patch
  - update
  - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-rolebinding
subjects:
- kind: ServiceAccount
  name: deploy-bp
  namespace: default
roleRef:
  kind: ClusterRole
  name: deploy-bp-role
  apiGroup: rbac.authorization.k8s.io